import { Event } from "../models/event";

export const events: Event[] = [
  {
    id: "4421cb3d-a0cf-4e29-8250-51767063cd62",
    artists: [{ name: "DJ's en vivo", description: "" }],
    category: "Sunset",
    collectionName: "Wine Activity #1",
    collectionSymbol: "WINE",
    createdAt: 1732388398000,
    date: "09 de Agosto, 2025",
    description:
      "Sunset wine & after orgnanizado por Paax Producciones.\n Degustación de más de 10 bodegas, plan Bonarda, dirección de Turismo y dirección de Cultura.\n YO 🤍 BONARDA",
    edition: 1,
    image: "/wine-activity-1.png",
    location: "Centro de congreso y exposiciones Francisco",
    locationLink: "https://maps.app.goo.gl/y3SvdpuJysCQcZyv9",
    name: "Wine Activity",
    prs: [
      {
        id: "3",
        name: "Agustina Chini",
        email: "agustinachini26@gmail.com",
        phone: "",
        photo: "",
        slug: "agustina-chini",
      },
      {
        id: "1",
        name: "Ana Paula Castillo",
        email: "Anapaulacastillo2323@gmail.com",
        phone: "",
        photo: "",
        slug: "ana-paula-castillo",
      },
      {
        id: "16",
        name: "Ailen Robles",
        email: "ailinrobles2@gmail.com",
        phone: "",
        photo: "",
        slug: "ailen-robles",
      },
      {
        id: "8",
        name: "Chiara Onofri",
        email: "Onofrichiarii@gmail.com",
        phone: "",
        photo: "",
        slug: "chiara-onofri",
      },
      {
        id: "15",
        name: "Candela Morello",
        email: "canndelamorello@gmail.com",
        phone: "",
        photo: "",
        slug: "candela-morello",
      },
      {
        id: "19",
        name: "Evelin Cabrera",
        email: "cabreraevelin88@gmail.com",
        phone: "",
        photo: "",
        slug: "evelin-cabrera",
      },
      {
        id: "2",
        name: "Emilia Suarez",
        email: "emiliasuarez818@gmail.com",
        phone: "",
        photo: "",
        slug: "emilia-suarez",
      },
      {
        id: "4",
        name: "Franco Pezutti",
        email: "pezuttifranco@gmail.com",
        phone: "",
        photo: "",
        slug: "franco-pezutti",
      },
      {
        id: "20",
        name: "Franco Sánchez",
        email: "francosanchezbts@gmail.com",
        phone: "",
        photo: "",
        slug: "franco-sanchez",
      },
      {
        id: "7",
        name: "Guadalupe Ledda",
        email: "Guadalupeledda010@gmail.com",
        phone: "",
        photo: "",
        slug: "guadalupe-ledda",
      },
      {
        id: "21",
        name: "Iván Jofre",
        email: "ivanjofre1506@gmail.com",
        phone: "",
        photo: "",
        slug: "ivan-jofre",
      },
      {
        id: "13",
        name: "Juan Vargas",
        email: "Juancito.vargass2@gmail.com",
        phone: "",
        photo: "",
        slug: "juan-vargas",
      },
      {
        id: "9",
        name: "Melisa Penna",
        email: "pennamelisa@gmail.com",
        phone: "",
        photo: "",
        slug: "melisa-penna",
      },
      {
        id: "11",
        name: "Mavi Fontana",
        email: "Mavi.fontana.costa@gmail.com",
        phone: "",
        photo: "",
        slug: "mavi-fontana",
      },
      {
        id: "22",
        name: "Martín Ruiz",
        email: "Martinruiz381@gmail.com",
        phone: "",
        photo: "",
        slug: "martin-ruiz",
      },
      {
        id: "5",
        name: "Tiago Carrasco",
        email: "Tiagoschoology@gmail.com",
        phone: "",
        photo: "",
        slug: "tiago-carrasco",
      },
      {
        id: "6",
        name: "Valentina Espin",
        email: "Valespin2001@icloud.com",
        phone: "",
        photo: "",
        slug: "valentina-espin",
      },
      {
        id: "10",
        name: "Victoria Ramírez",
        email: "victoriamilagrosr@gmail.com",
        phone: "",
        photo: "",
        slug: "victoria-ramirez",
      },
      {
        id: "17",
        name: "Victoria Lucero",
        email: "vickilucero19@gmail.com",
        phone: "",
        photo: "",
        slug: "victoria-lucero",
      },
      {
        id: "12",
        name: "Zeki Rivas",
        email: "ribasezekiel@gmail.com",
        phone: "",
        photo: "",
        slug: "zeki-rivas",
      },
      {
        id: "14",
        name: "Sabina Consoli",
        email: "consolini_96@hotmail.com",
        phone: "",
        photo: "",
        slug: "sabina-consoli",
      },
      {
        id: "18",
        name: "Renzo Guzmán",
        email: "guzmanrenzo76@gmail.com",
        phone: "",
        photo: "",
        slug: "renzo-guzman",
      },
    ],
    tickets: [
      {
        id: "d98c69a9-79f7-432c-a4f2-5e1e4bbd2cf5",
        description: "Copa de degustación + Entrada",
        name: "General",
        price: 17250,
        priceWithoutTax: 15000,
        tax: 2250,
        // price: 172.5,
        // priceWithoutTax: 150.0,
        // tax: 22.5,
        imageUrl: "https://d1ohydrg88i5oe.cloudfront.net/nft-images/wine-activity-1.png",
      },
    ],
    time: "19:00 hs - 02:00 hs",
  },
];
